import { TESTNET_WALRUS_PACKAGE_CONFIG, MAINNET_WALRUS_PACKAGE_CONFIG } from '@mysten/walrus';

console.log('TESTNET_WALRUS_PACKAGE_CONFIG:', JSON.stringify(TESTNET_WALRUS_PACKAGE_CONFIG, null, 2));
console.log('MAINNET_WALRUS_PACKAGE_CONFIG:', JSON.stringify(MAINNET_WALRUS_PACKAGE_CONFIG, null, 2));